### ISSUE TITLE
arm架构的adb没有找到可以使用pair的版本

### ISSUE THREAD

**Issue by locklocklock1206** [lx200916/ADB_Pair_Go#1]
您好，我在arm64架构下，并没有找到可以使用pair的adb版本，请问您的adb是在哪里找到的

**Comment by lx200916** [comment]
我使用的版本是33.0.2,输入`adb pair` 可以得到相关提示.在macOS(arm64)上使用的是brew包管理器直接安装.现在应该大部分包管理器仓库下的版本应该都支持adb pair了,尝试更新下试试?

**Comment by YsLtr** [comment]
> 我使用的版本是33.0.2,输入`adb pair` 可以得到相关提示.在macOS(arm64)上使用的是brew包管理器直接安装.现在应该大部分包管理器仓库下的版本应该都支持adb pair了,尝试更新下试试?

我也找不到可以使用pair的adb，在arm64架构，能否提供可以使用的adb包呢？

**Comment by lx200916** [comment]
> > 我使用的版本是33.0.2,输入`adb pair` 可以得到相关提示.在macOS(arm64)上使用的是brew包管理器直接安装.现在应该大部分包管理器仓库下的版本应该都支持adb pair了,尝试更新下试试?
> 
> 我也找不到可以使用pair的adb，在arm64架构，能否提供可以使用的adb包呢？

adb似乎是Platform-specific的,并不是跨平台的实现,所以我可能没办法很简单提供二进制包. 
可否给出你运行环境的adb版本信息,例如将`adb version`的所有输出信息贴给我?

**Comment by YsLtr** [comment]
> > > 我使用的版本是33.0.2,输入`adb pair` 可以得到相关提示.在macOS(arm64)上使用的是brew包管理器直接安装.现在应该大部分包管理器仓库下的版本应该都支持adb pair了,尝试更新下试试?
> > 
> > 
> > 我也找不到可以使用pair的adb，在arm64架构，能否提供可以使用的adb包呢？
> 
> adb似乎是Platform-specific的,并不是跨平台的实现,所以我可能没办法很简单提供二进制包. 可否给出你运行环境的adb版本信息,例如将`adb version`的所有输出信息贴给我?

好的，以下是`adb version`的输出内容
```
Android Debug Bridge version 1.0.41
Version 29.0.6-debian
Installed as /usr/lib/android-sdk/platform-tools/adb
```
还有截图
![image](https://github.com/lx200916/ADB_Pair_Go/assets/130123551/2fca26c4-1865-4737-a303-6d2c706c3082)

我不是专业的，但我在折腾的过程中发现只需要替换文件目录`/usr/lib/android-sdk/platform-tools/`中的`adb`文件就能改变版本，所以想请你看看能不能把你的adb文件复制出来

**Comment by lx200916** [comment]
> 我不是专业的，但我在折腾的过程中发现只需要替换文件目录`/usr/lib/android-sdk/platform-tools/`中的`adb`文件就能改变版本，所以想请你看看能不能把你的adb文件复制出来

从截图和版本来看,我猜测你可能用的是某个官方已经停止支持的Debian版本,比如Debian11 bullseye;或者使用Debian12 bookworm 但是没有添加backports源.
* 对于bullseye:很遗憾目前即使是在backports源内,adb包的版本也只更新到29,pair相关代码没有合入,因此没办法使用无线配对功能.由于adb包可能动态依赖一些系统基础库,你可能只能从源码自行编译.
* 对于bookworm: backports源的版本更新到了33,你可以添加backports源再重新安装adb相关组件,就能升级到有无线配对功能的adb客户端了.
> 至于你提到的替换adb文件的问题,adb程序可能会动态依赖一些系统基础库,因此我不确定从同架构同平台上简单移植是否可行,你也可以尝试从类似架构的高版本Debian系统上复制二进制文件进行尝试,但是我持有比较悲观的态度 😂

**Comment by YsLtr** [comment]
> > 我不是专业的，但我在折腾的过程中发现只需要替换文件目录`/usr/lib/android-sdk/platform-tools/`中的`adb`文件就能改变版本，所以想请你看看能不能把你的adb文件复制出来
> 
> 从截图和版本来看,我猜测你可能用的是某个官方已经停止支持的Debian版本,比如Debian11 bullseye;或者使用Debian12 bookworm 但是没有添加backports源.
> 
> * 对于bullseye:很遗憾目前即使是在backports源内,adb包的版本也只更新到29,pair相关代码没有合入,因此没办法使用无线配对功能.由于adb包可能动态依赖一些系统基础库,你可能只能从源码自行编译.
> * 对于bookworm: backports源的版本更新到了33,你可以添加backports源再重新安装adb相关组件,就能升级到有无线配对功能的adb客户端了.
> 
> > 至于你提到的替换adb文件的问题,adb程序可能会动态依赖一些系统基础库,因此我不确定从同架构同平台上简单移植是否可行,你也可以尝试从类似架构的高版本Debian系统上复制二进制文件进行尝试,但是我持有比较悲观的态度 😂

感谢你的提示，我试着给我的debian添加`bookworm: backports`源，但是更新后似乎并没有启用。
之后我在https://www.debian.org/distrib/packages 使用软件包搜索找到了更高版本的adb。
并且为了成功安装，我又手动查找了其需要的依赖包，一个个把依赖包给安装上去后终于成功装上了adb。最后也成功使用了`Pair`命令。
